### ISSUE TITLE
Release a version for stable rust?

### ISSUE THREAD

**Issue by orottier** [OrbitalStation/const-trig#3]
Cool library!
I was looking for a const f32 sine function for stable rust. Do you think it is possible to release a version or a new crate for this purpose so it can be used without nightly features?

**Comment by OrbitalStation** [comment]
Thanks for your kind words(and I'm really sorry for my late reply)! That would be great, but it would require removal of all const trait impls which will hurt UX. I think it is possible to release such a crate and/or a new version for the existing one but I don't really have enough interest nor time rn to implement it.

**Comment by OrbitalStation** [comment]
If you would be able to dedicate some time of yours to implement your feature I will be more than glad to accept it and list you as an author of the crate! It's just a proposal, I'm not trying to make you do my job for me, I just think that would be great :)

**Comment by orottier** [comment]
Hey, thanks for the reply.
I tried a few things but I'm afraid what I am asking is not possible at all.
Not just the const trait features are nightly only, but all const methods involving float values are!
`error[E0658]: floating point arithmetic is not allowed in constant functions`

**Comment by OrbitalStation** [comment]
Welp, you tried ¯\_(ツ)_/¯
Wait for stable support then)
